
build:
  version: "3.0"

accounts:
  message: "Welcome to EasyBanking accounts APIs"
  contactDetails:
    name: "Sylvia Developer"
    email: "sylviaachieng156@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345
