
build:
  version: "3.0"

loans:
  message: "Welcome to EasyBanking loans APIs"
  contactDetails:
    name: "Sylvia Developer"
    email: "sylviaachieng156@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-1345